name: CMake CI


on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:


env:
  CLICOLOR_FORCE: 1
  GTEST_COLOR: "yes"


jobs:
  clang_tidy:
    name: Clang Tidy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Configure CMake
        run: cmake --preset clang-release -DENABLE_UNIT_TESTS=OFF -DENABLE_CLANG_TIDY=ON # configure only needed for compile_commands.json

      - name: Run clang-tidy
        run: |
          clang-tidy --version
          run-clang-tidy \
            -p build/clang-release \
            src
  
  build:
    name: Build & Test (${{ matrix.os }} / ${{ matrix.type.preset }}
    runs-on: ${{ matrix.os }}
    needs: clang_tidy # Run build after clang-tidy succeeds

    strategy:
      # Set fail-fast to false to ensure that feedback is delivered for all matrix combinations.
      fail-fast: false

      # Set up a matrix to run the following configurations:
      # 1. Windows, Debug/Release, cl (uses VS multi config generator but is still split up for simplicity)
      # 2. Windows, Debug/Release, clang-cl
      # 3. Linux, Debug/Release, GCC
      # 4. Linux, Debug/Release, Clang
      # 5. MacOS, Debug/Release, Apple Clang
      matrix:
        os: [ubuntu-latest, macos-latest]
        type:
          - {preset: clang-debug,   config: Debug}
          - {preset: clang-release, config: Release}
          - {preset: gcc-debug,     config: Debug}
          - {preset: gcc-release,   config: Release}
        include:
          # Windows (MSVC)
          - os: windows-latest
            type: {preset: cl-debug, config: Debug}
          - os: windows-latest
            type: {preset: cl-release, config: Release}

          # Windows LLVM Clang (clang-cl)
          - os: windows-latest
            type: {preset: clang-cl-debug, config: Debug}
          - os: windows-latest
            type: {preset: clang-cl-release, config: Release}

        exclude:
          # macOS doesn't have GCC by default
          - os: macos-latest
            type: {preset: gcc-debug, config: Debug}
          - os: macos-latest
            type: {preset: gcc-release, config: Release}

    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Configure CMake
      run: cmake --preset ${{ matrix.type.preset }}
        
    - name: Build
      run: cmake --build --preset ${{ matrix.type.preset }} --verbose

    - name: Test
      run: ctest --preset ${{ matrix.type.preset }} --verbose

    - name: Install
      run: cmake --install build/${{ matrix.type.preset }} --config ${{ matrix.type.config }} # --config needed for multi config generators (MSVC)

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v6
      with:
        name: ${{ matrix.os }}-${{ matrix.type.preset }}-build
        path: ${{ github.workspace }}/build/${{ matrix.type.preset }}

    - name: Upload Installation
      uses: actions/upload-artifact@v6
      with:
        name: ${{ matrix.os }}-${{ matrix.type.preset }}-install
        path: ${{ github.workspace }}/install/${{ matrix.type.preset }}
    
  
  asan:
    name: ASan (${{ matrix.compiler }})
    runs-on: ubuntu-latest
    needs: build

    strategy:
      fail-fast: false
      matrix:
        include:
          - compiler: clang
            preset: clang-asan

          - compiler: gcc
            preset: gcc-asan

    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Configure CMake (ASan)
      run: cmake --preset ${{ matrix.preset }}

    - name: Build
      run: cmake --build --preset ${{ matrix.preset }} --verbose

    - name: Run Tests with ASan
      run: ctest --preset ${{ matrix.preset }} --verbose


  coverage:
    name: Code Coverage (llvm-cov)
    runs-on: ubuntu-latest
    needs: [build, asan]

    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Configure CMake
      run: cmake --preset clang-coverage

    - name: Build, Test, and Generate Coverage
      run: cmake --build --preset clang-coverage --verbose

    - name: Upload Coverage Report Artifact
      uses: actions/upload-artifact@v6
      with:
        name: llvm-cov-report
        path: ${{ github.workspace }}/coverage


  doxygen:
    name: Doxygen Documentation
    runs-on: ubuntu-latest
    needs: [build, asan]

    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Install Doxygen # NOTE: currently this installs an older version of Doxygen
      run: |
        sudo apt-get update -y
        sudo apt-get install -y doxygen

    - name: Generate Documentation
      run: doxygen Doxyfile

    - name: Upload Documentation Artifact
      uses: actions/upload-artifact@v6
      with:
        name: doxygen-documentation
        path: docs/html
