name: Clang Tidy
on:
  workflow_call: {}

jobs:
  clang_tidy:
    name: Clang Tidy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Configure CMake
        run: >
          cmake --preset clang-release -DENABLE_UNIT_TESTS=OFF -G Ninja

      - name: Run clang-tidy
        run: |
          run-clang-tidy \
            -p build/clang-release \
            src
