name: CMake CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:


env:
  BUILD_DIR: ${{ github.workspace }}/build

jobs:
  clang-tidy:
    uses: ./.github/workflows/clang-tidy.yml

  build:
    needs: clang-tidy
    uses: ./.github/workflows/build.yml

  asan:
    needs: build
    uses: ./.github/workflows/asan.yml

  coverage:
    needs: [build, asan]
    uses: ./.github/workflows/coverage.yml

  doxygen:
    needs: [build, asan]
    uses: ./.github/workflows/doxygen.yml
